server:
  port: 8090

spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/wms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: qiongbb
